# Generated by Django 2.2.5 on 2020-01-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0010_auto_20200123_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiranatureza', models.CharField(blank=True, choices=[('art.28', 'Art. 28. Usuário '), ('art.33', 'Art. 33. Trafico de Drogas'), ('Art.34', 'Art. 34. Maquinario '), ('Art.35', 'Art. 35. Associarem-se duas ou mais pessoas para o Trafico'), ('Art.36', 'Art. 36. Financiar Financiamento do Trafico:'), ('Art.121', 'Art.121. Matar Alguem'), ('art.155', 'Art. 155. Furto:'), ('art.157', 'Art. 157. Roubo:'), ('art.157§3º', 'Art 157. §3º - Roubo Com Lesão Corporal ; '), ('art.157§3º', 'Art 157. §3º -   Roubo Seguido de Morte (Latrocionio)  '), ('art.171', '  Art. 171. Estelionato:'), ('Lei.12850', 'Lei : 12850. Associação Criminosa ')], max_length=50, null=True, verbose_name='Primeira Natureza')),
                ('qualificacao', models.CharField(blank=True, choices=[('Aut', 'Autor'), ('Co-Aut', 'Co-Autor'), ('Part', 'Participe'), ('Vit', 'Vitima')], max_length=50, null=True)),
                ('segundanatureza', models.CharField(blank=True, choices=[('art.28', 'Art. 28. Usuário '), ('art.33', 'Art. 33. Trafico de Drogas'), ('Art.34', 'Art. 34. Maquinario '), ('Art.35', 'Art. 35. Associarem-se duas ou mais pessoas para o Trafico'), ('Art.36', 'Art. 36. Financiar Financiamento do Trafico:'), ('Art.121', 'Art.121. Matar Alguem'), ('art.155', 'Art. 155. Furto:'), ('art.157', 'Art. 157. Roubo:'), ('art.157§3º', 'Art 157. §3º - Roubo Com Lesão Corporal ; '), ('art.157§3º', 'Art 157. §3º -   Roubo Seguido de Morte (Latrocionio)  '), ('art.171', '  Art. 171. Estelionato:'), ('Lei.12850', 'Lei : 12850. Associação Criminosa ')], max_length=50, null=True, verbose_name='Segunda Natureza')),
                ('arma_de_fogo', models.CharField(blank=True, choices=[('Revolver', 'Revolver'), ('Pistola', 'Pistola'), ('Fac', 'Faca')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Vivo', 'Vivo'), ('Morto', 'Morto'), ('Preso', 'Preso'), ('Solto', 'Solto')], max_length=50, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rai', models.CharField(blank=True, max_length=100, null=True)),
                ('dataDoFato', models.DateField(verbose_name='Data do Fato')),
                ('descrição', models.CharField(blank=True, max_length=500, null=True)),
                ('infracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infracao.Infracao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Modusoperandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faccao', models.CharField(blank=True, choices=[('Nenhumas', 'Nenhuma'), ('PCC', 'PCC-Primeiro Comando da Capital'), ('Comando Vermelho', 'Comando Vermelho'), ('ADE', 'ADE')], max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, choices=[('Menbro', 'Membro'), ('Chefe', 'Chefe')], max_length=100, null=True)),
                ('infracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infracao.Infracao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
    ]
