# Generated by Django 2.2.5 on 2020-01-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200124_2342'),
        ('infracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modusoperandi',
            name='infracao',
        ),
        migrations.AddField(
            model_name='modusoperandi',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='faccao',
            field=models.CharField(blank=True, choices=[('Comando Vermelho', 'Comando Vermelho'), ('Nenhumas', 'Nenhuma'), ('PCC', 'PCC-Primeiro Comando da Capital'), ('ADE', 'ADE')], max_length=100, null=True),
        ),
    ]
