# Generated by Django 2.2.5 on 2020-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modusoperandi',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='ocorrencias',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='faccao',
            field=models.CharField(blank=True, choices=[('PCC', 'PCC-Primeiro Comando da Capital'), ('ADE', 'ADE'), ('Comando Vermelho', 'Comando Vermelho'), ('Nenhumas', 'Nenhuma')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Chefe', 'Chefe'), ('Menbro', 'Membro')], max_length=100, null=True),
        ),
    ]
