# Generated by Django 2.2.5 on 2020-01-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200124_2342'),
        ('infracao', '0002_auto_20200124_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencias',
            old_name='dataDoFato',
            new_name='data_do_fato',
        ),
        migrations.RenameField(
            model_name='ocorrencias',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='ocorrencias',
            name='infracao',
        ),
        migrations.AddField(
            model_name='ocorrencias',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='faccao',
            field=models.CharField(blank=True, choices=[('PCC', 'PCC-Primeiro Comando da Capital'), ('Nenhumas', 'Nenhuma'), ('ADE', 'ADE'), ('Comando Vermelho', 'Comando Vermelho')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Chefe', 'Chefe'), ('Menbro', 'Membro')], max_length=100, null=True),
        ),
    ]
