# Generated by Django 2.2.5 on 2020-01-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20191213_1002'),
        ('infracao', '0002_auto_20200106_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modusoperandi',
            name='infracao',
        ),
        migrations.RemoveField(
            model_name='ocorrencias',
            name='infracao',
        ),
        migrations.AddField(
            model_name='modusoperandi',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencias',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='faccao',
            field=models.CharField(blank=True, choices=[('PCC', 'PCC-Primeiro Comando da Capital'), ('Comando Vermelho', 'Comando Vermelho'), ('ADE', 'ADE'), ('Nenhumas', 'Nenhuma')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Menbro', 'Membro'), ('Chefe', 'Chefe')], max_length=100, null=True),
        ),
    ]
