# Generated by Django 2.2.5 on 2020-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracao', '0003_auto_20200124_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modusoperandi',
            name='faccao',
            field=models.CharField(blank=True, choices=[('ADE', 'ADE'), ('PCC', 'PCC-Primeiro Comando da Capital'), ('Nenhumas', 'Nenhuma'), ('Comando Vermelho', 'Comando Vermelho')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modusoperandi',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Menbro', 'Membro'), ('Chefe', 'Chefe')], max_length=100, null=True),
        ),
    ]
