# Generated by Django 2.2.5 on 2020-01-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracao', '0004_auto_20200129_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('funcao', models.CharField(blank=True, choices=[('Chefe', 'Chefe'), ('Membro', 'Membro')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Modusoperandi',
        ),
    ]
