# Generated by Django 2.2.5 on 2020-01-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('funcao', models.CharField(blank=True, choices=[('Chefe', 'Chefe'), ('Membro', 'Membro')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome')),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True, verbose_name='sobrenome')),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('mae', models.CharField(blank=True, max_length=50, null=True)),
                ('pai', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('faccao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoa.Faccao')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tatuagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_tatuagem', models.ImageField(upload_to='tatuagem', verbose_name='Imagem da Tatuagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Tatuagem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotopessoa', models.ImageField(upload_to='pessoa', verbose_name='Imagem da Pessoa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='UF')),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefone')], default='cel', max_length=10)),
                ('contato', models.CharField(max_length=50)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rai', models.CharField(blank=True, max_length=100, null=True)),
                ('data_do_fato', models.DateField(verbose_name='Data do Fato')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiranatureza', models.CharField(blank=True, choices=[('art.28', 'Art. 28. Usuário'), ('art.33', 'Art. 33. Trafico de Drogas'), ('Art.34', 'Art. 34. Maquinario'), ('Art.35', 'Art. 35. Associarem-se duas ou mais pessoas para o Trafico'), ('Art.36', 'Art. 36. Financiar Financiamento do Trafico'), ('Art.121', 'Art.121. Matar Alguem'), ('art.155', 'Art. 155. Furto'), ('art.157', 'Art. 157. Roubo'), ('art.157§3º', 'Art 157. §3º - Roubo Com Lesão Corporal'), ('art.157§3º', 'Art 157. §3º -   Roubo Seguido de Morte (Latrocinio)'), ('art.171', '  Art. 171. Estelionato'), ('Lei.12850', 'Lei : 12850. Associação Criminosa')], max_length=50, null=True, verbose_name='Primeira Natureza')),
                ('qualificacao', models.CharField(choices=[('aut', 'Autor'), ('coaut', 'Co-Autor'), ('part', 'Participe'), ('vit', 'Vitima')], default='aut', max_length=5)),
                ('segundanatureza', models.CharField(blank=True, choices=[('art.28', 'Art. 28. Usuário'), ('art.33', 'Art. 33. Trafico de Drogas'), ('Art.34', 'Art. 34. Maquinario'), ('Art.35', 'Art. 35. Associarem-se duas ou mais pessoas para o Trafico'), ('Art.36', 'Art. 36. Financiar Financiamento do Trafico'), ('Art.121', 'Art.121. Matar Alguem'), ('art.155', 'Art. 155. Furto'), ('art.157', 'Art. 157. Roubo'), ('art.157§3º', 'Art 157. §3º - Roubo Com Lesão Corporal'), ('art.157§3º', 'Art 157. §3º -   Roubo Seguido de Morte (Latrocinio)'), ('art.171', '  Art. 171. Estelionato'), ('Lei.12850', 'Lei : 12850. Associação Criminosa')], max_length=50, null=True, verbose_name='Segunda Natureza')),
                ('arma_de_fogo', models.CharField(blank=True, choices=[('revolver', 'Revolver'), ('pistola', 'Pistola'), ('faca', 'Faca')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('vivo', 'Vivo'), ('morto', 'Morto'), ('preso', 'Preso'), ('solto', 'Solto')], default='vivo', max_length=5)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Comparsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparsas', models.CharField(blank=True, max_length=100, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
    ]
