# Generated by Django 2.2.5 on 2019-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
