# Generated by Django 2.2.12 on 2020-07-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='status_atual',
            field=models.CharField(choices=[('foragido', 'Foragido'), ('morto', 'Morto'), (
                'preso', 'Preso'), ('solto', 'Solto')], default='foragido', max_length=8),
        ),
    ]
