# Generated by Django 2.2.5 on 2020-01-31 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparsa',
            name='comparsas',
        ),
        migrations.AddField(
            model_name='comparsa',
            name='nome_comparsa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='country',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.DeleteModel(
            name='PessoaEndereco',
        ),
    ]
