# Generated by Django 2.2.12 on 2020-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
    ]
