# Generated by Django 2.2.5 on 2019-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('tel', 'Telefone'), ('cel', 'Celular')], max_length=10),
        ),
    ]
