# Generated by Django 2.2.5 on 2020-01-31 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200131_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='pessoa.Ocorrencia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='pessoa.Pessoa')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
