# Generated by Django 2.2.5 on 2020-02-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200201_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoacontato',
            old_name='tipo_telefone',
            new_name='tipo',
        ),
    ]
