# Generated by Django 2.2.5 on 2020-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200124_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefone')], max_length=10),
        ),
    ]
