# Generated by Django 2.2.12 on 2020-07-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20200721_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pessoacomparsa',
            unique_together={('pessoa', 'comparsa')},
        ),
    ]
