# Generated by Django 2.2.5 on 2019-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20191117_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefone')], max_length=10),
        ),
    ]
