# Generated by Django 2.2.5 on 2020-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20200201_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='a', max_length=50, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(default='p', max_length=100, verbose_name='sobrenome'),
            preserve_default=False,
        ),
    ]
