# Generated by Django 2.2.12 on 2020-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20200723_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='observacao_comparsas',
            field=models.TextField(blank=True, null=True, verbose_name='Observação Comparsas'),
        ),
    ]
