# Generated by Django 2.2.5 on 2020-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20200215_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='país'),
        ),
    ]
