# Generated by Django 2.2.5 on 2019-11-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20191117_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafoto',
            name='fotoPessoa',
        ),
        migrations.AddField(
            model_name='pessoafoto',
            name='fotopessoa',
            field=models.ImageField(default=1, upload_to='media/pessoa', verbose_name='Imagem da Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('tel', 'Telefone'), ('cel', 'Celular')], max_length=10),
        ),
    ]
