# Generated by Django 2.2.7 on 2019-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20191118_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefone')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoafoto',
            name='fotopessoa',
            field=models.ImageField(upload_to='pessoa', verbose_name='Imagem da Pessoa'),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='fototatuagem',
            field=models.ImageField(upload_to='tatuagem', verbose_name='Imagem da Tatuagem'),
        ),
    ]
