# Generated by Django 2.2.12 on 2020-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_pessoa_observacao_comparsas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='observacao_bairro',
            field=models.TextField(blank=True, null=True, verbose_name='Observação Bairro'),
        ),
    ]
