# Generated by Django 2.2.5 on 2020-02-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20200215_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaveiculo',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_veiculos', to='pessoa.Pessoa'),
        ),
    ]
