# Generated by Django 2.2.10 on 2020-02-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20200216_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoafoto',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa'),
        ),
    ]
