# Generated by Django 2.2.5 on 2020-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20200131_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='arma',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
