# Generated by Django 2.2.7 on 2019-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20191130_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('tel', 'Telefone'), ('cel', 'Celular')], max_length=10),
        ),
    ]
