# Generated by Django 2.2.5 on 2020-01-31 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20200131_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ('modelo',),
            },
        ),
        migrations.AlterModelOptions(
            name='comparsa',
            options={'ordering': ('pessoa', 'nome_comparsa'), 'verbose_name': 'comparsa', 'verbose_name_plural': 'comparsas'},
        ),
        migrations.AlterModelOptions(
            name='faccao',
            options={'ordering': ('nome',), 'verbose_name': 'facção', 'verbose_name_plural': 'facções'},
        ),
        migrations.AlterModelOptions(
            name='infracao',
            options={'ordering': ('-created',), 'verbose_name': 'infração', 'verbose_name_plural': 'infrações'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'nome', 'verbose_name_plural': 'nomes'},
        ),
        migrations.AlterModelOptions(
            name='pessoacontato',
            options={'ordering': ('pessoa', 'contato'), 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterModelOptions(
            name='pessoafoto',
            options={'ordering': ('-created',), 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
        migrations.AlterModelOptions(
            name='tatuagem',
            options={'ordering': ('pessoa', '-created'), 'verbose_name': 'tatuagem', 'verbose_name_plural': 'tatuagens'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ('placa',), 'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
        migrations.AddField(
            model_name='comparsa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparsa',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infracao',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='pessoacontato',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoacontato',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='pessoafoto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafoto',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='tatuagem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tatuagem',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AlterField(
            model_name='faccao',
            name='funcao',
            field=models.CharField(blank=True, choices=[('chefe', 'Chefe'), ('membro', 'Membro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='pessoa.Modelo'),
            preserve_default=False,
        ),
    ]
