# Generated by Django 2.2.10 on 2020-02-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20200225_0236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PessoaFoto',
            new_name='Foto',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='fotopessoa',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='tatuagem',
            old_name='foto_tatuagem',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa'),
        ),
    ]
