# Generated by Django 2.2.5 on 2020-01-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_auto_20200115_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('tel', 'Telefone'), ('cel', 'Celular')], max_length=10),
        ),
    ]
