# Generated by Django 2.2.12 on 2020-10-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_auto_20200827_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='status_atual',
            field=models.CharField(choices=[('foragido', 'Foragido'), ('morto', 'Morto'), ('preso', 'Preso'), ('solto', 'Livre'), ('torno', 'Tornozelado')], default='foragido', max_length=8),
        ),
    ]
