# Generated by Django 2.2.10 on 2020-02-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_auto_20200225_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparsa',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
        ),
    ]
