# Generated by Django 2.2.5 on 2020-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20200122_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacontato',
            name='categoria',
            field=models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefone')], max_length=10),
        ),
    ]
