# Generated by Django 2.2.5 on 2020-01-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20200131_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.RenameField(
            model_name='pessoacontato',
            old_name='categoria',
            new_name='tipo_telefone',
        ),
    ]
