# Generated by Django 2.2.10 on 2020-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20200228_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparsa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoacontato',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
