# Generated by Django 2.2.5 on 2020-01-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_auto_20200131_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoacontato',
            options={'ordering': ('pessoa', 'telefone'), 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.RenameField(
            model_name='pessoacontato',
            old_name='contato',
            new_name='telefone',
        ),
    ]
