# Generated by Django 2.2.5 on 2020-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_auto_20200131_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='rai',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
