# Generated by Django 2.2.10 on 2020-03-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_auto_20200307_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='faccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoa.Faccao', verbose_name='facção'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mãe'),
        ),
    ]
