# Generated by Django 2.2.10 on 2020-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0012_auto_20200326_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparsa',
            name='grau_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comparsa',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comparsa',
            name='parente',
            field=models.BooleanField(default=False),
        ),
    ]
