# Generated by Django 2.2.5 on 2020-01-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0012_auto_20200131_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='primeira_natureza',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='segunda_natureza',
        ),
        migrations.AddField(
            model_name='infracao',
            name='natureza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturezas', to='pessoa.Natureza', verbose_name='natureza'),
        ),
    ]
