# Generated by Django 2.2.5 on 2020-01-31 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0013_auto_20200131_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparsa',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='comparsa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='comparsa',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='pessoaocorrencia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
    ]
