# Generated by Django 2.2.10 on 2020-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0014_auto_20200424_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparsa',
            name='parente',
            field=models.BooleanField(default=False),
        ),
    ]
