# Generated by Django 2.2.12 on 2020-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_auto_20200424_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='vitima',
            field=models.BooleanField(default=False),
        ),
    ]
