# Generated by Django 2.2.5 on 2020-02-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_auto_20200131_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='arma',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='natureza',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaveiculo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaveiculo',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrenciaveiculo',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='pessoaocorrencia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pessoaocorrencia',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='pessoaocorrencia',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Arma',
        ),
        migrations.DeleteModel(
            name='Infracao',
        ),
        migrations.DeleteModel(
            name='Natureza',
        ),
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
        migrations.DeleteModel(
            name='OcorrenciaVeiculo',
        ),
        migrations.DeleteModel(
            name='PessoaOcorrencia',
        ),
    ]
