# Generated by Django 2.2.24 on 2022-04-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0002_auto_20220428_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoria',
            old_name='nomeAutor',
            new_name='nomeautor',
        ),
        migrations.RenameField(
            model_name='autoria',
            old_name='sobrenomeAutor',
            new_name='sobrenomeautor',
        ),
    ]
