# Generated by Django 2.2.24 on 2022-04-28 19:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0003_auto_20220428_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('nomeautor', models.CharField(
                    max_length=50, verbose_name='nome autor')),
                ('sobrenomeautor', models.CharField(
                    max_length=50, verbose_name='sobre nome autor')),
            ],
            options={
                'verbose_name': 'nomeautor',
                'verbose_name_plural': 'nomeautores',
                'ordering': ('nomeautor',),
            },
        ),
        migrations.RemoveField(
            model_name='autoria',
            name='nomeautor',
        ),
        migrations.RemoveField(
            model_name='autoria',
            name='sobrenomeautor',
        ),
        migrations.AddField(
            model_name='homicidio',
            name='autor',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homicidio.Autor', verbose_name='Autor'),
        ),
    ]
