# Generated by Django 2.2.24 on 2022-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0005_auto_20220428_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diligencias',
        ),
        migrations.AddField(
            model_name='homicidio',
            name='diligencia',
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name='diligências'),
        ),
        migrations.AddField(
            model_name='homicidio',
            name='sobrenomeautor',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='sobrenome Autor'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='nomeautor',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='nome Autor'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
