# Generated by Django 2.2.24 on 2022-04-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0007_auto_20220428_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homicidio',
            old_name='sobrenomeautor',
            new_name='apelido',
        ),
    ]
