# Generated by Django 2.2.24 on 2022-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0008_auto_20220428_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='apelido'),
        ),
    ]
