# Generated by Django 2.2.24 on 2022-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homicidio', '0009_auto_20220428_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicidio',
            name='apelidovitima',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='apelido vítima'),
        ),
    ]
