# Generated by Django 2.2.10 on 2020-04-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_auto_20200307_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
