# Generated by Django 2.2.10 on 2020-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_veiculo_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
    ]
