# Generated by Django 2.2.12 on 2020-07-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='arma',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='natureza',
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infracao.Arma'),
        ),
        migrations.DeleteModel(
            name='Arma',
        ),
        migrations.DeleteModel(
            name='Infracao',
        ),
        migrations.DeleteModel(
            name='Natureza',
        ),
    ]
