# Generated by Django 2.2.5 on 2020-02-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0003_auto_20200201_2241'),
        ('ocorrencia', '0002_auto_20200201_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaUpm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_upm', models.CharField(max_length=50, unique=True, verbose_name='área UPM')),
            ],
            options={
                'verbose_name': 'area upm',
                'verbose_name_plural': 'area upms',
                'ordering': ('area_upm',),
            },
        ),
        migrations.CreateModel(
            name='Motivacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='título')),
            ],
            options={
                'verbose_name': 'motivação',
                'verbose_name_plural': 'motivações',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Homicidio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço')),
                ('address_number', models.IntegerField(blank=True, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='país')),
                ('data_do_homicidio', models.DateField(verbose_name='Data do Homicídio')),
                ('forma', models.CharField(choices=[('tentado', 'Tentado'), ('consumado', 'Consumado')], default='tentado', max_length=10)),
                ('area_upm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.AreaUpm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencia.Arma')),
                ('motivacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Motivacao')),
                ('rai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencia.Ocorrencia')),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
            options={
                'verbose_name': 'homicídio',
                'verbose_name_plural': 'homicídios',
                'ordering': ('-data_do_homicidio',),
            },
        ),
    ]
