# Generated by Django 2.2.5 on 2020-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_areaupm_homicidio_motivacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='país'),
        ),
    ]
