# Generated by Django 2.2.5 on 2020-02-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_auto_20200215_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa'),
        ),
    ]
