# Generated by Django 2.2.10 on 2020-02-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_auto_20200215_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaocorrencia',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias1', to='ocorrencia.Ocorrencia'),
        ),
        migrations.AlterField(
            model_name='pessoaocorrencia',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_ocorrencias', to='pessoa.Pessoa'),
        ),
    ]
