# Generated by Django 2.2.10 on 2020-03-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_auto_20200225_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='status',
            field=models.CharField(choices=[('foragido', 'Foragido'), ('morto', 'Morto'), ('preso', 'Preso'), ('solto', 'Solto')], default='Foragido', max_length=5),
        ),
    ]
