# Generated by Django 2.2.10 on 2020-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0007_auto_20200307_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='status',
            field=models.CharField(choices=[('foragido', 'Foragido'), ('morto', 'Morto'), ('preso', 'Preso'), ('solto', 'Solto')], default='foragido', max_length=8),
        ),
    ]
