# Generated by Django 2.2.10 on 2020-03-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0010_natureza_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='area_upm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.AreaUpm', verbose_name='área UPM'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='motivacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Motivacao', verbose_name='homicídio'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='rai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencia.Ocorrencia', verbose_name='rai da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='qualificacao',
            field=models.CharField(choices=[('aut', 'Autor'), ('coaut', 'Co-Autor'), ('part', 'Participe'), ('vit', 'Vitima')], default='aut', max_length=5, verbose_name='qualificação'),
        ),
    ]
