# Generated by Django 2.2.10 on 2020-03-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0011_auto_20200317_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='motivacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Motivacao', verbose_name='motivação'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='vitima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='vítima'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='rai',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAI'),
        ),
    ]
