# Generated by Django 2.2.10 on 2020-04-22 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0012_auto_20200326_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('autoria', models.CharField(max_length=50, verbose_name='autoria')),
            ],
            options={
                'verbose_name': 'autoria',
                'verbose_name_plural': 'autorias',
                'ordering': ('autoria',),
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('genero', models.CharField(max_length=50, verbose_name='genero')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'ordering': ('genero',),
            },
        ),
        migrations.AddField(
            model_name='homicidio',
            name='autoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Autoria', verbose_name='Autoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homicidio',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Genero', verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
