# Generated by Django 2.2.12 on 2020-05-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0013_auto_20200422_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='vitima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='vítima'),
        ),
    ]
