# Generated by Django 2.2.12 on 2020-05-02 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0014_auto_20200501_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicidio',
            name='autoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.Autoria', verbose_name='Autoria'),
        ),
        migrations.AlterField(
            model_name='homicidio',
            name='vitima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='vítima'),
            preserve_default=False,
        ),
    ]
